PAYONE-GmbH/shopware-5

Frontend/MoptPaymentPayone/Controllers/Backend/FcPayone.php, Frontend/MoptPaymentPayone/Views/backend/fc_payone/apilog.tpl, Frontend/MoptPaymentPayone/Views/backend/fc_payone/transactionlog.tpl
Apilog und transaktionslogs: falsche Darstellung von Live und Testmodus
=> Projekt 5stars+

Frontend/MoptPaymentPayone/Bootstrap.php
Shopware 5.2 doesn't seem to catch the method signature used here anymore and rewrites it to the array parameter used by Doctrine\ORM\EntityRepository::findOneBy() thus causing a fatal error when installing the plugin.
=> Shopware 5.2 compatibility

Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php, Frontend/MoptPaymentPayone/Subscribers/BackendOrder.php, Frontend/MoptPaymentPayone/Subscribers/BackendPayment.php, Frontend/MoptPaymentPayone/Subscribers/BackendRiskManagement.php, Frontend/MoptPaymentPayone/Subscribers/Document.php, Frontend/MoptPaymentPayone/Subscribers/EMail.php, Frontend/MoptPaymentPayone/Subscribers/FrontendAccount.php, Frontend/MoptPaymentPayone/Subscribers/FrontendCheckout.php, Frontend/MoptPaymentPayone/Subscribers/FrontendPostDispatch.php, Frontend/MoptPaymentPayone/Subscribers/Payment.php, Frontend/MoptPaymentPayone/Subscribers/Resource.php
This should fix a lot of errors identified using the standard Shopware phpunit test suites and enable merchants to use a CD workflow. However, backwards compatibility is not clear yet.
Changes and their test results in detail:
* Unmodified MoptPaymentPayone:
Tests: 988, Assertions: 5397, Errors: 94, Failures: 18, Skipped: 63.
* Added \Shopware\Components\DependencyInjection\ before every Container in Subscriber registration:
Tests: 988, Assertions: 5168, Errors: 97, Failures: 22, Skipped: 63.
* Changed Enlight_Event_EventArgs to \Enlight_Controller_ActionEventArgs
Tests: 1024, Assertions: 6093, Errors: 40, Failures: 20, Skipped: 27.
* Fixed Enlight_Event_EventArgs to \Enlight_Event_EventArgs in Resource.php
Tests: 1028, Assertions: 7082, Errors: 7, Failures: 17, Skipped: 23.
* Fixed …
=> Fixed a load of namespace and type hinting errors

Frontend/MoptPaymentPayone/Bootstrap.php
The duplicate subscription created a problem that VAT was added twice when the price of a position in the order was changed in the backend.
=> Removed duplicate BackendOrder subscription (fixes TPI-1526)

Frontend/MoptPaymentPayone/Bootstrap.php, Frontend/MoptPaymentPayone/Components/Classes/PayoneInstallHelper.php, Frontend/MoptPaymentPayone/Components/Payone/Api/Response/Interface.php, Frontend/MoptPaymentPayone/Models/MoptPayoneApiLog/MoptPayoneApiLog.php, Frontend/MoptPaymentPayone/Models/MoptPayoneApiLog/Repository.php
This change save transaction id in own database table field.
Sometimes it's necessary to search by transaction id, it's much easily and faster with an own field.
=> save transaction id in own database table field

Frontend/MoptPaymentPayone/Bootstrap.php, Frontend/MoptPaymentPayone/Subscribers/PayoneResource.php
‘resource’ is a soft reserved word as of PHP 7.
Therefore this class needed to be refactored.
=> Refactor the subscriber Resource -> PayoneResource

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php
This is causing Exceptions when trying to debit a Payolution B2B order (internal reference TPI-1663)
=> Remove unneccessary VAT ID parameter from Payolution Debit

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php
If there is no shipment information, we currently generate a bogus order item, i.e. things like the `id` value are missing from the item. This causes certain payment processing services to refuse the order. In order to avoid that, we must only add an order item for shipment information, if it is actually present.
=> Only add shipment as an order item if present

Frontend/MoptPaymentPayone/Components/Classes/PayonePaymentHelper.php
The usual way to read values from the Shopware order atrributes array unfortunately is broken. Therefore shop admins could access this value only in a Shopware owned variable that was not documented by PAYONE. Now the value ‘txid’ from API responses will also be stored with the key ‘clearing_txid’ in the clearing data array for easier access in mail templates:
`{$additional.moptPayoneClearingData.clearing_txid}`
=> Store the transaction ID together with clearing data (SW-67)

Frontend/MoptPaymentPayone/Subscribers/Payment.php
The plugin didn't save the payment data into the database. After digging deeper, we found out, that the wrong POST parameters were looked at (register[payment] instead of payment).
This is probably because, we disabled account registration on our checkout.
=> Fix payments for non-registered accounts

Frontend/MoptPaymentPayone/Controllers/Frontend/MoptAjaxPayone.php
- get paymentId from userData instead from session
- added logging for payolution installment calculation requests
=> SW-97-payolution-bugfix: calculation request uses wrong paymentid

Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentEcs.php
- after returning from paypal redirect to checkout-confirm instead of shippingpayment
- this was prevented by not setting a session variable
=> SW-110-paypal: bugfix

Frontend/MoptPaymentPayone/Components/Classes/PayoneHelper.php
- using sGetUserData() could trigger an endless cascade of addresschecks
when triggered by a risk rule
=> SW-112-Addresschecks

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php
Auch Gutscheine und Zuschläge haben eine Bestellnummer. Diese wird hier verwendet. Außerdem wird die Bestellnummer für normale Artikel ebenfalls in der Länge beschränkt um Fehlercode 1611 zu verhindern.
=> use ordernumber in ParamBuilder

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php
Behebt zu langen ID Parameter wenn der Name der Versandart sehr lang ist (Fehlercode 1611).
=> fix long shipping names in param builder

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php
Dieser PR fixt den Fehlercode 1610 (Article list incomplete or faulty) beim Absetzen einer Bestellung mit Ratepay. Dieser kommt zu Stande, wenn der Betrag der einzelnen Positionen nicht mit dem Gesamtbetrag übereinstimmt. Dies rührt von einem Rundungsfehlers beim Berechnen des Positionspreises her.
=> fix error code 1610 (Article list incomplete or faulty)

Frontend/MoptPaymentPayone/Components/Classes/PayoneMain.php
We got a fatal error in some cases on a staging system:
PHP Fatal error: Uncaught Error: Cannot use object of type Shopware\CustomModels\MoptPayoneConfig\MoptPayoneConfig as array in ../engine/Shopware/Plugins/Community/Frontend/MoptPaymentPayone/Components/Classes/PayonePaymentHelper.php:1303
=> The Fallback in this function creates an Object and returns it. The normal process returns an array
=> hotfix for returned object instead of array

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php
* paypal does not allow negative article positions marked as handling
so map these as vouchers
* this issue was caused by the SwagAdvancedPromotion Suite which uses
article mode 4 for vouchers instead of shipping
=> SW-163: fixed paypal issue with negative basket positions

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php
Fixes #308 
Given a multi byte string article description (for instance containing `ß`) shortening using `substr()` won't work and lead to errors at the Payone API.
=> Make shortening of article description multibyte-safe

Frontend/MoptPaymentPayone/Views/frontend/checkout/ajax_cart_amazon.tpl, Frontend/MoptPaymentPayone/Views/frontend/checkout/mopt_cart_amazon.tpl
Extend if-clause for detection of ssl to be more flexible in distributed environments using loadbalancers.
Has been tested with one of our customers and works as expected.
Fixes #333
=> improved ssl detection in templates

Frontend/MoptPaymentPayone/Components/Payone/Api/Service/Payment/Preauthorize.php, Frontend/MoptPaymentPayone/Controllers/Backend/FcPayone.php
* fixed issue when using preauthorize from fcPayone backend controller
=> SW-353: added successurl param for connection test

Frontend/MoptPaymentPayone/Controllers/Backend/FcPayone.php, Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxaddresscheck.tpl, Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxconfig.tpl, Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxcreditcard.tpl, Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxdebit.tpl, Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxfinance.tpl, Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxgeneralconfig.tpl, Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxonlinetransfer.tpl, Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxpaymentstatusconfig.tpl, Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxriskcheck.tpl, Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxtransactionstatusconfig.tpl, Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxwallet.tpl
* re-added exit after json output and added ignore for the automatic shopware review
=> SW-448: fixed automatic form filling for new control center

Frontend/MoptPaymentPayone/Views/frontend/_resources/javascript/mopt_payment.js
Replace potentially dangerous eval() call. Severity rating medium (CVSS Score 4.5). Creates issues with PCI DSS ASV scans.
=> Dangerous JS Functio eval() -  PCI DSS ASV Scan issue
