PAYONE-GmbH/shopware-5

Frontend/MoptPaymentPayone/composer.lock
composer.lock

see https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file

adding composer.lock files to vcs because it's recommend by composer.

---

Frontend/MoptPaymentPayone/Controllers/Backend/FcPayone.php
Frontend/MoptPaymentPayone/Controllers/Backend/MoptPayoneRatepay.php
Frontend/MoptPaymentPayone/Models/MoptPayoneRatepay/MoptPayoneRatepay.php

Configs that were removed by the user in the submitted form now get deleted

(SW-62) Fix the saveRatepayConfigsAction

---

Frontend/MoptPaymentPayone/Bootstrap.php
Frontend/MoptPaymentPayone/Components/Classes/PayoneInstallHelper.php

This eliminates the deprecation warnings in Bootstrap.php -> partially fixes #41 (SW-49)

Refactor addAttributes() and removeAttributes()

---

Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentPayone.php

* fixed passing of errormessages to error template

(SW-64) - Fehlernachricht wird nicht korrekt ausgegeben

---

Frontend/MoptPaymentPayone/Bootstrap.php
Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php
Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentPayone.php
Frontend/MoptPaymentPayone/Subscribers/FrontendPostDispatch.php

added documentation (github issue #44 )
some bugfixes regarding capture/refund (github issue #48)

SW 60 better custom capture refund

---

Frontend/MoptPaymentPayone/Views/frontend/plugins/payment/mopt_paymentmean_ratepay_invoice.tpl

fixed indents
removed  some CRLF's

do not show birthday fields if in b2b mode

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneFormHandler.php
Frontend/MoptPaymentPayone/Controllers/Frontend/MoptAjaxPayone.php
Frontend/MoptPaymentPayone/Views/frontend/_resources/styles/ratepay.css
Frontend/MoptPaymentPayone/Views/frontend/plugins/payment/mopt_paymentmean_ratepay_installment.tpl

- rate amount field is now marked red after validation failure
- error message for rate amount field is now properly translated

#SW-80-ratepay-installments

---

Frontend/MoptPaymentPayone/Bootstrap.php

- fixed wrong 4th parameter in getInvoicingFromOrder() call
has to be true for refunds

SW-85: GH issue #83

---

Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentPayone.php

- address changes on confirm page are now accouted for

SW-98-change-address-on-confirm: address changes on checkout confirm

---

Frontend/MoptPaymentPayone/Controllers/Frontend/MoptAjaxPayone.php
Frontend/MoptPaymentPayone/Views/frontend/plugins/payment/mopt_paymentmean_payolution_installment.tpl

- removed payment mean check from ajax precheck call, this prevented
the correct functioning on account controller
- display snippet based error message instead of static error

payolution-installments: bugfixes

---

Frontend/MoptPaymentPayone/Subscribers/FrontendPostDispatch.php

SW-107: fixed: payolution companyname not set

---

Frontend/MoptPaymentPayone/Views/frontend/checkout/mopt_cart.tpl

fixed missing parent: in checkout cart template

SW-108-checkout-template

---

Frontend/MoptPaymentPayone/Views/conecxoResponsive/frontend/account/mopt_billing_responsive.tpl
Frontend/MoptPaymentPayone/Views/conecxoResponsive/frontend/account/mopt_consumescore_responsive.tpl
Frontend/MoptPaymentPayone/Views/conecxoResponsive/frontend/checkout/mopt_confirm_payment_responsive.tpl
Frontend/MoptPaymentPayone/Views/conecxoResponsive/frontend/checkout/mopt_confirm_responsive.tpl
Frontend/MoptPaymentPayone/Views/conecxoResponsive/frontend/checkout/mopt_finish_responsive.tpl
Frontend/MoptPaymentPayone/Views/conecxoResponsive/frontend/mopt_payment_payone/download_error.tpl
Frontend/MoptPaymentPayone/Views/conecxoResponsive/frontend/mopt_payment_payone/error.tpl
Frontend/MoptPaymentPayone/Views/frontend/account/mopt_billing.tpl
Frontend/MoptPaymentPayone/Views/frontend/account/mopt_consumescore.tpl
Frontend/MoptPaymentPayone/Views/frontend/account/mopt_shipping.tpl
Frontend/MoptPaymentPayone/Views/frontend/checkout/ajax_cart.tpl
Frontend/MoptPaymentPayone/Views/frontend/checkout/mopt_cart.tpl
Frontend/MoptPaymentPayone/Views/frontend/checkout/mopt_confirm.tpl
Frontend/MoptPaymentPayone/Views/frontend/checkout/mopt_finish.tpl
Frontend/MoptPaymentPayone/Views/frontend/checkout/mopt_shipping_confirm.tpl
Frontend/MoptPaymentPayone/Views/frontend/checkout/mopt_shipping_payment.tpl
Frontend/MoptPaymentPayone/Views/frontend/checkout/mopt_shipping_payment_core.tpl
Frontend/MoptPaymentPayone/Views/frontend/mopt_payment_payone/creditcard_iframe.tpl
Frontend/MoptPaymentPayone/Views/frontend/mopt_payment_payone/download_error.tpl
Frontend/MoptPaymentPayone/Views/frontend/mopt_payment_payone/error.tpl
Frontend/MoptPaymentPayone/Views/frontend/mopt_payment_payone/payolution_error.tpl
Frontend/MoptPaymentPayone/Views/frontend/mopt_payment_payone/ratepay_error.tpl
Frontend/MoptPaymentPayone/Views/frontend/moptaddresspayone/edit.tpl

- removed append and prepend smarty tags
- added parent to extends tags

SW-108-Checkouttemplate Problem:  fixed template inheritance

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneHelper.php
Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php

- fixed bug where shipping address gets checked although it is equal to billing address
- fixed forward to non-existing controller for SW 5.2.X
- fixed attribute handling for SW 5.2.X

SW-112-addresscheck: bugfixes

---

Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentEcs.php

- deleted user additional dublicates and wrong assigns

- deleted unessesary if statements

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php

Set correct length for cart item id param

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneHelper.php
Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php

This pull request fixes an issue that caused address check results not to have impact on executed risk rules in some Shopware versions. Additionally a possible stack overflow has also been fixed.

SW-120: Fix bugs in handling of risk rules and address checks

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php

* otherwise multiple captures are impossible

SW-123: force settleaccount = no for paypal captures

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php

SW-136 - fixed check for orderpositions with taxID = 0

---

Frontend/MoptPaymentPayone/Controllers/Backend/MoptPayoneOrder.php

* always use settaccount=auto when capturing
* do not send capturemode parameter when capturing
* always send mandatory basket content when capturing

SW-149: PO Safe Invoice changes

---

Frontend/MoptPaymentPayone/Bootstrap.php
Frontend/MoptPaymentPayone/Components/Classes/PayoneInstallHelper.php
Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentPayone.php

* also corrects payolution setting from auth to  preauth in case auth was set by accident

SW-146: removed hard coded payolution auth setting

---

Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentEcs.php

* unset workorderid after PPE user cancel to allow finishing the order with
"normal" PP

SW-142: bugfix paypal:

---

Frontend/MoptPaymentPayone/Subscribers/FrontendPostDispatch.php

SW-151: cleanup $session['sComment'] on finish page

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php
Frontend/MoptPaymentPayone/Controllers/Backend/MoptPayoneOrder.php

* fixed shopid not transmitted when capturing ratepay payments

SW-150: verified / fixed manual captures

---

Frontend/MoptPaymentPayone/Views/frontend/mopt_payment_payone/error.tpl

* fixed bug where session gets lost after cancelling payments
and clicking "Zahlart ändern"

SW-154: session lost after payment cancel

---

Frontend/MoptPaymentPayone/Subscribers/FrontendPostDispatch.php

* get paymentId from view instead of the whole sGetUserData array
* fixes #188

SW-159: ignore ajaxEditor actions in FrontendPostdispatch subscriber

---

Frontend/MoptPaymentPayone/Components/Classes/PayonePaymentHelper.php
Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php
Frontend/MoptPaymentPayone/Subscribers/FrontendCheckout.php
Frontend/MoptPaymentPayone/Subscribers/FrontendPostDispatch.php
Frontend/MoptPaymentPayone/Subscribers/Paymentfilter.php

* read basket amount and user paymentid from session in some cases
* cleaned up parameters of moptGetRatePayConfig()

SW-182: replaced some costly calls to sGetBasket

---

Frontend/MoptPaymentPayone/Controllers/Frontend/MoptAjaxPayone.php

SW-117-invalid-timestamp: fixed invalid timestamp when expirymonth is 12

---

Frontend/MoptPaymentPayone/Subscribers/FrontendPostDispatch.php

* led to saving brutto orders as net
* fixes #248

SW-197: fixed unintended removal of charge_vat flag

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneMain.php
Frontend/MoptPaymentPayone/Subscribers/OrderNumber.php
Frontend/MoptPaymentPayone/Views/backend/fc_payone/ajaxgeneralconfig.tpl
Frontend/MoptPaymentPayone/Views/backend/mopt_config_payone/view/main/detail.js

Create Shopware ordernumber instead of mopt-xxxxxxxxxx

---

Frontend/MoptPaymentPayone/Subscribers/Payment.php

* this issue was only reproducible with SwagBusinessEssentials active

SW-212: fixed issue with paypal orders switching fom netto to brutto

---

Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentEcs.php

* this led to logged in users switching the customer group

SW_212: do not create a user on paypal return if already logged in

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneHelper.php
Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php
Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php

* prevent addresschecks for packstation addresses
* prefix shipping_street with "Packstation" for Payone API compatibility

SW-207: added compatibility to "Wunschpaket" Packstation addresses

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneMain.php
Frontend/MoptPaymentPayone/Controllers/Frontend/MoptShopNotification.php
Frontend/MoptPaymentPayone/Subscribers/OrderNumber.php

* this happend when backend setting sendOrdernumberAsReference
* was set to false for some payment types

SW-223 fixed ordernumbers not sequential in some cases

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php

Sw-228 - removed sessionid from url

---

Frontend/MoptPaymentPayone/Subscribers/Payment.php

Reverts PAYONE-GmbH/shopware-5#291

Revert "SW-212: correct net flag when using business essentials plugin"

---

Frontend/MoptPaymentPayone/Controllers/Frontend/MoptShopNotification.php

SW-244: Add logging, when session could not be restored, or sOrderVariables is malformed

SW-244: Add logging, when session could not be restored

---

Frontend/MoptPaymentPayone/Subscribers/Payment.php

Corrected Intendation
Added Payment Grouping Events
Fixes #296 
Thanks @danielDigitalArt

SW-248: Finalized Pull-Request 298 / code style adjustment

---

Frontend/MoptPaymentPayone/Subscribers/FrontendCheckout.php

Fix wrong payment id transferred to session

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneUserHelper.php
Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentPayDirekt.php
Frontend/MoptPaymentPayone/Controllers/Frontend/MoptPaymentPayone.php
Frontend/MoptPaymentPayone/Views/frontend/checkout/mopt_confirm.tpl

disable address change buttons on checkout/confirm only for paydirekt express

SW-285: bugfix paydirekt express

---

Frontend/MoptPaymentPayone/Views/frontend/plugins/payment/mopt_paymentmean_klarna.tpl

SW-294: Fix Klarna birth year selector

---

Frontend/MoptPaymentPayone/Snippets/frontend/MoptPaymentPayone/errorMessages.ini
Frontend/MoptPaymentPayone/Subscribers/AddressCheck.php
Frontend/MoptPaymentPayone/Subscribers/FrontendPostDispatch.php
Frontend/MoptPaymentPayone/Views/frontend/plugins/payment/mopt_paymentmean_klarna.tpl

* in case of address changes redirect the user back to shippingpayment and inform him why

SW-324: klarna payments: handle address changes on confirm page

---

Frontend/MoptPaymentPayone/Controllers/Frontend/MoptAjaxPayone.php

* fixed compatibility issue in ajax request for shopware versions older than 5.6
Fixes #387

SW-323: fixed paysafe payments for old shopware versions

---

Frontend/MoptPaymentPayone/Bootstrap.php

*  before installing cronjob, check if cronjob action already exists in old naming scheme

SW-326: bugfix: cronjob created in old SW version leads to duplicate entry in s_crontab

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneConfig.php

SW-366: Add payment method PayPal to account page

---

Frontend/MoptPaymentPayone/Components/Classes/PayoneParamBuilder.php
Frontend/MoptPaymentPayone/Components/Classes/PayonePaymentHelper.php
Frontend/MoptPaymentPayone/Components/Payone/Api/Request/Genericpayment.php
Frontend/MoptPaymentPayone/Controllers/Frontend/MoptAjaxPayone.php
Frontend/MoptPaymentPayone/Snippets/frontend/MoptPaymentPayone/errorMessages.ini
Frontend/MoptPaymentPayone/Subscribers/FrontendPostDispatch.php
Frontend/MoptPaymentPayone/Subscribers/Payment.php
Frontend/MoptPaymentPayone/Views/frontend/_resources/javascript/mopt_klarna_shipping_payment.js
Frontend/MoptPaymentPayone/Views/frontend/_resources/javascript/mopt_payment.js
Frontend/MoptPaymentPayone/Views/frontend/checkout/mopt_shipping_payment_core.tpl
Frontend/MoptPaymentPayone/Views/frontend/plugins/payment/mopt_paymentmean_klarna.tpl

* fixed birthday not saved when using klarna payments in ungrouped mode

SW-425: fixed some issues with phone number handling for klarna payments

---

README.md

New Features
* Secured Invoice (BNPL) extension for B2B customers, deviant delivery address allowed
Bugfixes
* fixed Unzer Payments optional Birthday field
* fixed handling of shipping costs for PayPal Express
* adjustments & fixes regarding COF (credentialsOnFile)
Removed features
* Removed Schufa configuration from Protect
Maintenance
* tested with 5.7.18 
* PHP-Version 8.2
* MySql 8.0

version bump to 4121

---

README.md

New Features
* Secured Invoice (BNPL) extension for B2B customers, deviant delivery address allowed
Bugfixes
* fixed Unzer Payments optional Birthday field
* fixed handling of shipping costs for PayPal Express
* adjustments & fixes regarding COF (credentialsOnFile)
Removed features
* Removed Schufa configuration from Protect
Maintenance
* tested with 5.7.18 
* PHP-Version 8.2
* MySql 8.0

version bump to 4122

---

README.md

New Features
* Secured Invoice (BNPL) extension for B2B customers, deviant delivery address allowed
Bugfixes
* Fixed Unzer Payments optional Birthday field
* Fixed handling of shipping costs for PayPal Express
* Adjustments & fixes regarding COF (credentialsOnFile)
* Fixed problems with uploading to shopware store
Removed features
* Removed Schufa configuration from Protect
Maintenance
* tested with 5.7.18 
* PHP-Version 8.2
* MySql 8.0

version bump to 4125

---

README.md

Bugfixes
* fixed amount mismatch on Apple Pay
* fixed automatic form filling in our control center
Maintenance
* updated the iDEAL issuer list
* updated the hash method
* removed paydirekt and updated giropay
tested with 5.7.19

version bump to 4130

---

composer.json

Bugfixes
* fixed amount mismatch on Apple Pay
* fixed automatic form filling in our control center
Maintenance
* updated the iDEAL issuer list
* updated the hash method
* removed paydirekt and updated giropay
tested with 5.7.19

version bump to 4132

---

README.md

New Features
* New payment method: PayPal v2
* New payment method: PayPal v2 Express
Bugfix
* Create creditcard user attribute when missing
Maintenance
* Removed iDEAL bank groups
* Tested with 5.7.19

version bump to 4140

---

Frontend/MoptPaymentPayone/Bootstrap.php

* due to differing doctrine model definition and actual table state

SW-462: fixed sql exception during module update

---

Frontend/MoptPaymentPayone/Subscribers/FrontendAccount.php
Frontend/MoptPaymentPayone/Views/frontend/plugins/payment/mopt_paymentmean_creditcard.tpl

* to make it possible to change default payment from creditcard to other payments when no creditcard data was saved previously
* fixes issue #534

SW-467: remove required from creditcard fields on account page

---

README.md

New Features
* new payment method: Google Pay
Bugfixes
* fixes for PAYONE_Footer and PAYONE_Content_Info document extension elements
* fixed database exceptions after manually deleting attribute columns
* fixed invoice generation for payone secured invoice
* fixes for pdf invoice generation
Maintenance
* remove required from creditcard fields on account page
* tested with 5.7.19

version bump to 4150
